blank_issues_enabled: false
contact_links:
  - name: Getting Started
    url: https://callstack.github.io/react-native-paper/getting-started.html
    about: Read how to get started with react-native-paper.
  - name: Documentation
    url: https://callstack.github.io/react-native-paper/index.html
    about: Read the official documentation.
  - name: Example
    url: https://snack.expo.io/@react-native-paper/github.com-callstack-react-native-paper:example
    about: See the official example app.
  - name: Contributing guide
    url: https://github.com/callstack/react-native-paper/blob/main/CONTRIBUTING.md
    about: See our contributing guide.
  - name: Discord channel
    url: https://discord.com/channels/426714625279524876/438316503113138176
    about: Join to our official discord channel.
